import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/providers/query-provider';
import { TradingProvider } from '@/providers/trading-context';
import { ThemeProvider } from '@/components/theme-provider';
import { PriceFeed } from '@/providers/price-feed';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <QueryProvider>
          <TradingProvider>
            <body className={inter.className}>
              <PriceFeed />
              {children}
            </body>
          </TradingProvider>
        </QueryProvider>
      </ThemeProvider>
    </html>
  );
}
